server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.nzuodengmseqtamdjpwd
    password: coMMon$0$
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Uncomment this only if you use Spring Mail (SMTP), not Resend API
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: pqenirob@gmail.com
#    password: "vjps ouwr grbb klet"
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

resend:
  api-key: "re_RHkuCprs_Esoes5TRockAH7s3sv4wq25z"

email:
  from: "itsmahfuz.com.au"
